### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [filipevarjao/sphinx#23]
Can you please throw an Apache license file into the repository and issue a pull request containing the changes to the downstream ESL fork please. Rather have the repository under CI there.

**Comment by maiphuong-van** [comment]
Can you check this PR: [https://github.com/esl/sphinx/pull/1](https://github.com/esl/sphinx/pull/1 )? I added the license but it also added the new commit merge from master, I don't know how to leave them out :/

**Comment by maiphuong-van** [comment]
Commit merged
